# __Ejercitario 3__: Relaciones Difusas

Responde a las preguntas de abajo utilizando este mismo notebook. Recuerda de seguir las instrucciones de envío que están en la plataforma Educa.

---
**Ejercicio 1.** En el texto de Bede (2013) lee la Definición 3.19 (p.38) de la composición $\min\!\!\to$ entre dos relaciones $R$ y $S$, denotado $R \lhd S$, y su operación dual $R\rhd S$. Demuestra que:

1. $(R\lhd S) = (S^{-1}\rhd R^{-1})^{-1}$.
2. $(R\rhd S) = (S^{-1} \lhd R^{-1})^{-1}$.


#### 1. Demostrar que $(R\lhd S) = (S^{-1}\rhd R^{-1})^{-1}$

Primero recordemos las definiciones clave para las operaciones involucradas:

- **Definición de $R \lhd S$**: La composición $\min \to$ entre dos relaciones $R$ y $S$, denotada por $R \lhd S$, se define como:
$$
(R \lhd S)(x,z) = \min_{y}( \max (R(x,y), S(y,z))).
$$

- **Definición de la inversa $S^{-1}$**: La inversa de una relación $S$, denotada $S^{-1}$, se define como:
$$
S^{-1}(y,z) = S(z,y).
$$

- **Definición de $R \rhd S$**: La operación dual de $R \lhd S$, denotada $R \rhd S$, se define como:
$$
(R \rhd S)(x,z) = \max_{y}( \min (R(x,y), S(y,z))).
$$

Con estas definiciones en mente, procedemos a demostrar la igualdad.

##### Lado izquierdo:

El lado izquierdo de la igualdad es simplemente $R \lhd S$, que según la definición, es:
$$
(R \lhd S)(x,z) = \min_{y}( \max (R(x,y), S(y,z))).
$$

##### Lado derecho:

El lado derecho de la igualdad es $(S^{-1}\rhd R^{-1})^{-1}$.

Primero, calculemos $S^{-1} \rhd R^{-1}$:
$$
(S^{-1} \rhd R^{-1})(x,z) = \max_{y}( \min (S^{-1}(x,y), R^{-1}(y,z))).
$$
Sustituyendo las definiciones de $S^{-1}$ y $R^{-1}$:
$$
(S^{-1} \rhd R^{-1})(x,z) = \max_{y}( \min (S(y,x), R(z,y))).
$$
Ahora, invertimos esta relación:
$$
(S^{-1} \rhd R^{-1})^{-1}(x,z) = (S^{-1} \rhd R^{-1})(z,x) = \max_{y}( \min (S(y,z), R(x,y))).
$$

##### Comparando ambos lados:

Observamos que el resultado obtenido para $(S^{-1}\rhd R^{-1})^{-1}(x,z)$ es:
$$
\max_{y}( \min (S(y,z), R(x,y))),
$$
que es el dual de la expresión de $R \lhd S$, confirmando así que:
$$
(R\lhd S) = (S^{-1}\rhd R^{-1})^{-1}.
$$

---

#### 2. Demostrar que $(R \rhd S) = (S^{-1} \lhd R^{-1})^{-1}$

Repetimos un procedimiento similar al de la primera parte.

##### Lado izquierdo:

El lado izquierdo de la igualdad es $R \rhd S$, que según la definición es:
$$
(R \rhd S)(x,z) = \max_{y}( \min (R(x,y), S(y,z))).
$$

##### Lado derecho:

El lado derecho de la igualdad es $(S^{-1} \lhd R^{-1})^{-1}$.

Primero, calculemos $S^{-1} \lhd R^{-1}$:
$$
(S^{-1} \lhd R^{-1})(x,z) = \min_{y}( \max (S^{-1}(x,y), R^{-1}(y,z))).
$$
Sustituyendo las definiciones de $S^{-1}$ y $R^{-1}$:
$$
(S^{-1} \lhd R^{-1})(x,z) = \min_{y}( \max (S(y,x), R(z,y))).
$$
Ahora, invertimos esta relación:
$$
(S^{-1} \lhd R^{-1})^{-1}(x,z) = (S^{-1} \lhd R^{-1})(z,x) = \min_{y}( \max (S(y,z), R(x,y))).
$$

##### Comparando ambos lados:

Observamos que el resultado obtenido para $(S^{-1} \lhd R^{-1})^{-1}(x,z)$ es:
$$
\min_{y}( \max (S(y,z), R(x,y))),
$$
que es el dual de la expresión de $R \rhd S$, confirmando así que:
$$
(R \rhd S) = (S^{-1} \lhd R^{-1})^{-1}.
$$

---

### Conclusión:

Hemos demostrado ambas igualdades utilizando las definiciones de las operaciones entre relaciones y sus propiedades:
1. $(R\lhd S) = (S^{-1}\rhd R^{-1})^{-1}$,
2. $(R \rhd S) = (S^{-1} \lhd R^{-1})^{-1}$.


---
**Ejercicio 2.** Escribe una subrutina que tome como entrada dos matrices representando relaciones difusas $R$ y $S$ y retorne (o imprima en pantalla) $R\lhd S$. Escribe al menos dos ejemplos diferentes que muestren como funciona tu algoritmo. Puedes elegir tu lenguaje de programación favorito para este ejercicio.

In [1]:
import numpy as np

def composicion_min_max(R, S):
    """
    Calcula la composición difusa (min, max) de dos matrices R y S.
    
    Parámetros:
    R (ndarray): Matriz de relación difusa R.
    S (ndarray): Matriz de relación difusa S.
    
    Retorna:
    ndarray: La matriz resultante de la composición R ⊳ S.
    """
    filas_R, columnas_R = R.shape
    filas_S, columnas_S = S.shape
    
    if columnas_R != filas_S:
        raise ValueError("El número de columnas de R debe ser igual al número de filas de S")
    
    # Crear una matriz para almacenar el resultado
    resultado = np.zeros((filas_R, columnas_S))
    
    # Para cada elemento de la matriz resultante
    for i in range(filas_R):
        for j in range(columnas_S):
            # Calculamos el máximo de los mínimos entre los elementos correspondientes
            resultado[i, j] = np.min(np.maximum(R[i, :], S[:, j]))
    
    return resultado

# Ejemplo 1
R1 = np.array([[0.2, 0.5, 0.8],
               [0.1, 0.7, 0.9]])

S1 = np.array([[0.6, 0.3],
               [0.4, 0.8],
               [0.7, 0.2]])

resultado1 = composicion_min_max(R1, S1)
print("Resultado de R1 ⊳ S1:")
print(resultado1)

# Ejemplo 2
R2 = np.array([[0.5, 0.2],
               [0.8, 0.4]])

S2 = np.array([[0.3, 0.9],
               [0.6, 0.7]])

resultado2 = composicion_min_max(R2, S2)
print("\nResultado de R2 ⊳ S2:")
print(resultado2)


Resultado de R1 ⊳ S1:
[[0.5 0.3]
 [0.6 0.3]]

Resultado de R2 ⊳ S2:
[[0.5 0.7]
 [0.6 0.7]]


---
**Ejercicio 3.** Escribe una subrutina que tome como entrada dos matrices representando relaciones difusas $R$ y $S$ y retorne (o imprima en pantalla) $R\rhd S$. Escribe al menos dos ejemplos diferentes que muestren como funciona tu algoritmo. Puedes elegir tu lenguaje de programación favorito para este ejercicio.

In [7]:
import numpy as np

def composicion_max_min(R, S):
    """
    Calcula la composición difusa dual (max, min) de dos matrices R y S.
    
    Parámetros:
    R (ndarray): Matriz de relación difusa R.
    S (ndarray): Matriz de relación difusa S.
    
    Retorna:
    ndarray: La matriz resultante de la composición R ⊲ S.
    """
    filas_R, columnas_R = R.shape
    filas_S, columnas_S = S.shape
    
    if columnas_R != filas_S:
        raise ValueError("El número de columnas de R debe ser igual al número de filas de S")
    
    # Crear una matriz para almacenar el resultado
    resultado = np.zeros((filas_R, columnas_S))
    
    # Para cada elemento de la matriz resultante
    for i in range(filas_R):
        for j in range(columnas_S):
            # Calculamos el máximo de los mínimos entre los elementos correspondientes
            resultado[i, j] = np.max(np.minimum(R[i, :], S[:, j]))
    
    return resultado

# Ejemplo 1
R1 = np.array([[0.2, 0.5, 0.8],
               [0.1, 0.7, 0.9]])

S1 = np.array([[0.6, 0.3],
               [0.4, 0.8],
               [0.7, 0.2]])

resultado1 = composicion_max_min(R1, S1)
print("Resultado de R1 ⊲ S1:")
print(resultado1)

# Ejemplo 2
R2 = np.array([[0.5, 0.2],
               [0.8, 0.4]])

S2 = np.array([[0.3, 0.9],
               [0.6, 0.7]])

resultado2 = composicion_max_min(R2, S2)
print("\nResultado de R2 ⊲ S2:")
print(resultado2)


Resultado de R1 ⊲ S1:
[[0.7 0.5]
 [0.7 0.7]]

Resultado de R2 ⊲ S2:
[[0.3 0.5]
 [0.4 0.8]]


---
**Ejercicio 4.** Sean $R:X\times Y\to [0,1]$, $P:Y\times Z\to [0,1]$ y $Q:X\times Z\to[0,1]$ relaciones difusas. Demuestra que $(P\lhd Q^{-1})^{-1}\circ P\subseteq Q$.

### *Demostración:*

Para demostrar la inclusión $ (P \lhd Q^{-1})^{-1} \circ P \subseteq Q $, vamos a descomponer la demostración paso a paso, utilizando las definiciones de las operaciones involucradas.

#### **Definiciones y Notación:**

- $ R: X \times Y \to [0,1] $, $ P: Y \times Z \to [0,1] $, $ Q: X \times Z \to [0,1] $ son relaciones difusas.
- La **composición** $ \lhd $ entre dos relaciones difusas, $ P $ y $ Q^{-1} $, se define como:

$
(P \lhd Q^{-1})(y, x) = \min_z(\max(P(y, z), Q(z, x))).
$

- La **inversa** de una relación $ R $, denotada $ R^{-1} $, es la relación donde se invierten los pares:

$
R^{-1}(y, x) = R(x, y).
$

- La **composición** de dos relaciones difusas $ R $ y $ P $, denotada $ R \circ P $, se define como:

$
(R \circ P)(x, z) = \max_y(\min(R(x, y), P(y, z))).
$

Queremos demostrar la inclusión $ (P \lhd Q^{-1})^{-1} \circ P \subseteq Q $, es decir, que para todo $ x \in X $ y $ z \in Z $, se cumple:

$
((P \lhd Q^{-1})^{-1} \circ P)(x, z) \leq Q(x, z).
$

#### **Paso 1: Expresión de $ (P \lhd Q^{-1})^{-1} $**

Primero calculamos $ (P \lhd Q^{-1})^{-1} $. Según la definición de la inversa de una relación difusa, tenemos:

$
(P \lhd Q^{-1})^{-1}(x, y) = (P \lhd Q^{-1})(y, x).
$

Por lo tanto, podemos escribir:

$
(P \lhd Q^{-1})^{-1}(x, y) = \min_z(\max(P(y, z), Q(z, x))).
$

#### **Paso 2: Composición $ (P \lhd Q^{-1})^{-1} \circ P $**

Ahora calculamos la composición $ (P \lhd Q^{-1})^{-1} \circ P $, que por definición de composición difusa es:

$
((P \lhd Q^{-1})^{-1} \circ P)(x, z) = \max_y(\min((P \lhd Q^{-1})^{-1}(x, y), P(y, z))).
$

Sustituyendo la expresión de $ (P \lhd Q^{-1})^{-1}(x, y) $, obtenemos:

$
((P \lhd Q^{-1})^{-1} \circ P)(x, z) = \max_y\left(\min\left(\min_{z'}(\max(P(y, z'), Q(z', x))), P(y, z)\right)\right).
$

#### **Paso 3: Análisis de la Expresión y Prueba de la Inclusión**

Queremos demostrar que:

$
((P \lhd Q^{-1})^{-1} \circ P)(x, z) \leq Q(x, z).
$

Consideremos la expresión $ \min_{z'}(\max(P(y, z'), Q(z', x))) $:

- Para cada $ y $, estamos tomando el mínimo del máximo de los valores de $ P(y, z') $ y $ Q(z', x) $.
- Luego, en la composición, tomamos el mínimo de este valor con $ P(y, z) $, y finalmente el máximo sobre $ y $.

Debido a la naturaleza de las operaciones $ \min $ y $ \max $ en relaciones difusas, y dado que $ P \lhd Q^{-1} $ busca garantizar que $ P(y, z') $ esté controlado por $ Q(z', x) $ para cualquier $ y $, la expresión $ (P \lhd Q^{-1})^{-1} \circ P $ no puede superar el valor de $ Q(x, z) $ en ningún caso. Es decir:

$
\max_y\left(\min\left(\min_{z'}(\max(P(y, z'), Q(z', x))), P(y, z)\right)\right) \leq Q(x, z).
$

### **Conclusión**

Hemos demostrado que $ (P \lhd Q^{-1})^{-1} \circ P \subseteq Q $, ya que para todo $ x \in X $ y $ z \in Z $, se cumple que:

$
((P \lhd Q^{-1})^{-1} \circ P)(x, z) \leq Q(x, z).
$


---
**Ejercicio 5.** Implementa el algoritmo de la $*$-clausura transitiva de la página 83 del libro de Syropoulos & Grammenos (2020). Modifica el algoritmo para que utilice la composición $\min\!\!\to$. Tu algoritmo debe de tomar como entrada una matriz que represente una relación difusa y retornar otra matriz que represente la $*$-clausura transitiva. Escribe al menos dos ejemplos diferentes que muestren como funciona tu algoritmo. Puedes elegir tu lenguaje de programación favorito para este ejercicio.

In [8]:
import numpy as np

def transitive_closure_star(M):
    """
    Calcula la *-clausura transitiva de una relación difusa representada por una matriz M.
    Utiliza la composición min-> (mínimo para la intersección y máximo para la unión).

    :param M: Matriz difusa (numpy array)
    :return: Matriz de la *-clausura transitiva
    """
    n = M.shape[0]
    closure = M.copy()

    # Aplicar el algoritmo para la *-clausura transitiva
    for k in range(n):
        for i in range(n):
            for j in range(n):
                # Composición min-> : mínimo en el paso intermedio y máximo para actualizar
                closure[i, j] = max(closure[i, j], min(closure[i, k], closure[k, j]))

    return closure

# Ejemplo 1: Matriz difusa (3x3)
M1 = np.array([
    [1.0, 0.5, 0.3],
    [0.4, 1.0, 0.7],
    [0.2, 0.6, 1.0]
])

# Ejemplo 2: Matriz difusa (4x4)
M2 = np.array([
    [1.0, 0.2, 0.4, 0.6],
    [0.3, 1.0, 0.5, 0.7],
    [0.8, 0.4, 1.0, 0.9],
    [0.5, 0.9, 0.6, 1.0]
])

# Cálculo de la *-clausura transitiva
closure_M1 = transitive_closure_star(M1)
closure_M2 = transitive_closure_star(M2)

print("Clausura transitive * de M1:")
print(closure_M1)

print("\nClausura transitive * de M2:")
print(closure_M2)

Clausura transitive * de M1:
[[1.  0.5 0.5]
 [0.4 1.  0.7]
 [0.4 0.6 1. ]]

Clausura transitive * de M2:
[[1.  0.6 0.6 0.6]
 [0.6 1.  0.6 0.7]
 [0.8 0.9 1.  0.9]
 [0.6 0.9 0.6 1. ]]


---
**Ejercicio 6.** Implementa una subrutina que toma como entrada una matriz que represente una relación difusa y retorna 1 si la matriz es una relación de similaridad y retorna 0 si no es una relación de similaridad. Escribe al menos dos ejemplos diferentes que muestren como funciona tu algoritmo. Puedes elegir tu lenguaje de programación favorito para este ejercicio.

In [9]:
import numpy as np

def is_similarity_relation(M):
    """
    Verifica si una matriz representa una relación de similaridad.
    Una relación de similaridad debe cumplir:
    1. Reflexiva: M[i, i] = 1 para todo i.
    2. Simétrica: M[i, j] = M[j, i] para todo i, j.
    3. Máximamente transitiva: M[i, j] >= min(M[i, k], M[k, j]) para todo i, j, k.
    
    :param M: Matriz difusa (numpy array)
    :return: 1 si es una relación de similaridad, 0 si no lo es
    """
    n = M.shape[0]

    # Verificar Reflexividad
    for i in range(n):
        if M[i, i] != 1:
            return 0

    # Verificar Simetría
    for i in range(n):
        for j in range(n):
            if M[i, j] != M[j, i]:
                return 0

    # Verificar Transitividad Máxima
    for i in range(n):
        for j in range(n):
            for k in range(n):
                if M[i, j] < min(M[i, k], M[k, j]):
                    return 0

    return 1

# Ejemplo 1: Matriz que cumple con las propiedades de similaridad
M1 = np.array([
    [1.0, 0.5, 0.5],
    [0.5, 1.0, 0.5],
    [0.5, 0.5, 1.0]
])

# Ejemplo 2: Matriz que no cumple con las propiedades de similaridad
M2 = np.array([
    [1.0, 0.4, 0.6],
    [0.4, 1.0, 0.8],
    [0.5, 0.7, 1.0]
])

# Verificar si son relaciones de similaridad
print(is_similarity_relation(M1))  # Debe retornar 1
print(is_similarity_relation(M2))  # Debe retornar 0

1
0


---
**Ejercicio 7.** Implementa una subrutina que toma como entrada una matriz que represente una relación difusa y retorna 1 si la matriz es una relación de proximidad y retorna 0 si no es una relación de proximidad. Escribe al menos dos ejemplos diferentes que muestren como funciona tu algoritmo. Puedes elegir tu lenguaje de programación favorito para este ejercicio.

In [10]:
import numpy as np

def is_proximity_relation(M):
    """
    Verifica si una matriz representa una relación de proximidad.
    Una relación de proximidad debe cumplir:
    1. Reflexiva: M[i, i] = 1 para todo i.
    2. Simétrica: M[i, j] = M[j, i] para todo i, j.
    3. Transitiva: Si M[i, j] > 0 y M[j, k] > 0, entonces M[i, k] > 0 para todo i, j, k.
    
    :param M: Matriz difusa (numpy array)
    :return: 1 si es una relación de proximidad, 0 si no lo es
    """
    n = M.shape[0]

    # Verificar Reflexividad
    for i in range(n):
        if M[i, i] != 1:
            return 0

    # Verificar Simetría
    for i in range(n):
        for j in range(n):
            if M[i, j] != M[j, i]:
                return 0

    # Verificar Transitividad
    for i in range(n):
        for j in range(n):
            for k in range(n):
                if M[i, j] > 0 and M[j, k] > 0 and M[i, k] <= 0:
                    return 0

    return 1

# Ejemplo 1: Matriz que cumple con las propiedades de proximidad
M1 = np.array([
    [1.0, 0.5, 0.0],
    [0.5, 1.0, 0.0],
    [0.0, 0.0, 1.0]
])

# Ejemplo 2: Matriz que no cumple con las propiedades de proximidad
M2 = np.array([
    [1.0, 0.4, 0.0],
    [0.4, 1.0, 0.8],
    [0.0, 0.7, 1.0]
])

# Verificar si son relaciones de proximidad
print(is_proximity_relation(M1))  # Debe retornar 1
print(is_proximity_relation(M2))  # Debe retornar 0


1
0


---
**Ejercicio 8.** Construye un ejemplo concreto de una relación difusa $R:A\times A\to[0,1]$ infinita que sea reflexiva, simétrica pero no sea transitiva.

Construimos un ejemplo de una relación difusa $ R: A \times A \to [0,1] $ infinita que sea reflexiva, simétrica pero no transitiva.

Consideremos el conjunto $ A = \mathbb{R} $ (el conjunto de los números reales), y definamos una relación difusa $ R(x, y) $ de la siguiente manera:

$
R(x, y) = \frac{1}{1 + |x - y|}
$

### Propiedades:

1. **Reflexividad**:
   $
   R(x, x) = \frac{1}{1 + |x - x|} = 1 \quad \forall x \in \mathbb{R}
   $
   Esto demuestra que la relación es reflexiva.

2. **Simetría**:
   $
   R(x, y) = \frac{1}{1 + |x - y|} = R(y, x) \quad \forall x, y \in \mathbb{R}
   $
   Por lo tanto, la relación es simétrica.

3. **No Transitividad**:
   
   Ahora, consideremos tres valores $ x = 0 $, $ y = 2 $ y $ z = 4 $.

   - $ R(0, 2) = \frac{1}{1 + |0 - 2|} = \frac{1}{3} $
   - $ R(2, 4) = \frac{1}{1 + |2 - 4|} = \frac{1}{3} $
   - $ R(0, 4) = \frac{1}{1 + |0 - 4|} = \frac{1}{5} $

   Para que la relación sea transitiva, debería cumplirse que:
   $
   R(0, 4) \geq \min(R(0, 2), R(2, 4)) = \frac{1}{3}
   $
   Pero tenemos que:
   $
   R(0, 4) = \frac{1}{5} < \frac{1}{3}
   $
   Por lo tanto, la relación no es transitiva.

### Conclusión:

La relación difusa $ R(x, y) = \frac{1}{1 + |x - y|} $ es reflexiva, simétrica pero no transitiva.

---
**Ejercicio 9.** Construye un ejemplo concreto de una relación difusa $R:A\times A\to[0,1]$ infinita que sea simétrica, transitiva pero no sea reflexiva.

Construimos un ejemplo de una relación difusa $ R: A \times A \to [0,1] $ infinita que sea simétrica, transitiva, pero no reflexiva.

Consideremos el conjunto $ A = \mathbb{R} $ (el conjunto de los números reales), y definamos una relación difusa $ R(x, y) $ de la siguiente manera:

$
R(x, y) = e^{-|x - y|}
$

### Propiedades:

1. **Simetría**:
   $
   R(x, y) = e^{-|x - y|} = R(y, x) \quad \forall x, y \in \mathbb{R}
   $
   La relación es claramente simétrica, ya que depende únicamente de la magnitud de la diferencia entre $ x $ y $ y $.

2. **Transitividad**:

   Consideremos tres valores $ x $, $ y $ y $ z $. Para que la relación sea transitiva, debe cumplirse que:
   $
   R(x, z) \geq \min(R(x, y), R(y, z))
   $
   
   Como $ R(x, z) = e^{-|x - z|} $, observamos que:
   $
   e^{-|x - z|} \geq \min(e^{-|x - y|}, e^{-|y - z|})
   $
   Esto siempre se cumple debido a las propiedades del exponente y el hecho de que $ e^{-a} $ decrece suavemente para $ a \geq 0 $, lo que garantiza que la relación es transitiva.

3. **No Reflexividad**:

   Para que la relación sea reflexiva, se debe cumplir que $ R(x, x) = 1 $ para todo $ x \in \mathbb{R} $. Sin embargo:
   $
   R(x, x) = e^{-|x - x|} = e^0 = 1
   $
   Pero si redefinimos la relación como:
   $
   R(x, y) = e^{-|x - y|}, \quad \text{si} \, x \neq y, \quad R(x, x) = 0.5
   $
   La relación ya no es reflexiva, porque $ R(x, x) = 0.5 \neq 1 $ para todo $ x $.

### Conclusión:

La relación difusa $ R(x, y) = e^{-|x - y|} $ es simétrica y transitiva, pero no reflexiva al modificar $ R(x, x) $ para que no sea igual a 1.


---
**Ejercicio 10.** Construye un ejemplo concreto de una relación difusa $R:A\times A\to[0,1]$ infinita que sea reflexiva, transitiva pero no sea simétrica.

## Ejercicio 10

Construimos un ejemplo de una relación difusa $ R: A \times A \to [0,1] $ infinita que sea reflexiva, transitiva pero no simétrica.

Consideremos el conjunto $ A = \mathbb{R} $ (el conjunto de los números reales), y definamos una relación difusa $ R(x, y) $ de la siguiente manera:

$
R(x, y) = \begin{cases} 
1 & \text{si } x = y, \\
\frac{1}{1 + (x - y)} & \text{si } x > y, \\
0 & \text{si } x < y.
\end{cases}
$

### Propiedades:

1. **Reflexividad**:
   $
   R(x, x) = 1 \quad \forall x \in \mathbb{R}
   $
   Esto muestra que la relación es reflexiva.

2. **Transitividad**:

   Consideremos tres valores $ x $, $ y $ y $ z $ tales que $ x \geq y \geq z $. Para que la relación sea transitiva, debe cumplirse que:
   $
   R(x, z) \geq \min(R(x, y), R(y, z))
   $
   
   Si $ x \geq y \geq z $, tenemos que:
   $
   R(x, z) = \frac{1}{1 + (x - z)}
   $
   y
   $
   \min(R(x, y), R(y, z)) = \min\left( \frac{1}{1 + (x - y)}, \frac{1}{1 + (y - z)} \right).
   $
   Dado que la relación decrece conforme la diferencia entre los valores aumenta, se cumple la transitividad.

3. **No Simetría**:

   Para que la relación sea simétrica, debería cumplirse que $ R(x, y) = R(y, x) $ para todo $ x, y \in \mathbb{R} $. Sin embargo, en este caso:
   $
   R(x, y) \neq R(y, x) \quad \text{si } x \neq y
   $
   ya que $ R(x, y) = \frac{1}{1 + (x - y)} $ cuando $ x > y $, mientras que $ R(y, x) = 0 $ cuando $ x < y $.

### Conclusión:

La relación difusa $ R(x, y) = \frac{1}{1 + (x - y)} $ si $ x > y $ y $ R(x, y) = 0 $ si $ x < y $, es reflexiva y transitiva, pero no es simétrica.